
package MyCabService;

import java.awt.Component;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class BookRide extends javax.swing.JFrame {

    /**
     * Creates new form BookRide
     */
    private final ArrayList<Integer> value = new ArrayList<>();
    
    int TotalFare = 0;
    private String name;
    
    public BookRide(String name, Component cmp) {
        FlatLook.setup();
        initComponents();
        this.name = name;
        loadFields();
        value.add(0);
        this.setLocationRelativeTo(cmp);
    }

    private void loadFields(){
        cmbPickLocation.removeAllItems();
        cmbDropLocation.removeAllItems();
        cmbPickLocation.addItem("[ ---- Select ----]");
        cmbDropLocation.addItem("[ ---- Select ----]");
        try {
            ResultSet rs = DataBaseConnection.getData("SELECT * FROM Locations");
            while(rs.next()){
                cmbPickLocation.addItem(rs.getString(2));
                cmbDropLocation.addItem(rs.getString(2));
                value.add(rs.getInt(3));
            }
        } catch (Exception e) {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cmbPickLocation = new javax.swing.JComboBox();
        cmbDropLocation = new javax.swing.JComboBox();
        cmbVehicle = new javax.swing.JComboBox();
        txtDistance = new javax.swing.JTextField();
        txtFare = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(566, 498));
        setPreferredSize(new java.awt.Dimension(566, 498));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbPickLocation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        cmbPickLocation.setForeground(new java.awt.Color(63, 63, 63));
        cmbPickLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select ---" }));
        cmbPickLocation.setMinimumSize(new java.awt.Dimension(0, 23));
        cmbPickLocation.setPreferredSize(new java.awt.Dimension(0, 23));
        cmbPickLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPickLocationActionPerformed(evt);
            }
        });

        cmbDropLocation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        cmbDropLocation.setForeground(new java.awt.Color(63, 63, 63));
        cmbDropLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Select ---" }));
        cmbDropLocation.setEnabled(false);
        cmbDropLocation.setMinimumSize(new java.awt.Dimension(0, 23));
        cmbDropLocation.setPreferredSize(new java.awt.Dimension(0, 23));
        cmbDropLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDropLocationActionPerformed(evt);
            }
        });

        cmbVehicle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        cmbVehicle.setForeground(new java.awt.Color(63, 63, 63));
        cmbVehicle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[ --- Select --- ]", "Bike", "Rikshaw", "Mini Ride", "AC Ride", "Premium Class" }));
        cmbVehicle.setMinimumSize(new java.awt.Dimension(0, 23));
        cmbVehicle.setPreferredSize(new java.awt.Dimension(0, 23));
        cmbVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVehicleActionPerformed(evt);
            }
        });

        txtDistance.setEditable(false);
        txtDistance.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        txtDistance.setForeground(new java.awt.Color(63, 63, 63));
        txtDistance.setText("0");
        txtDistance.setMinimumSize(new java.awt.Dimension(0, 23));
        txtDistance.setPreferredSize(new java.awt.Dimension(0, 23));

        txtFare.setEditable(false);
        txtFare.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        txtFare.setForeground(new java.awt.Color(63, 63, 63));
        txtFare.setText("Rs ");
        txtFare.setMinimumSize(new java.awt.Dimension(0, 23));
        txtFare.setPreferredSize(new java.awt.Dimension(0, 23));

        jButton1.setBackground(new java.awt.Color(79, 166, 241));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book Ride");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Your Location :");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Drop Off Location :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Total Distance :");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Cab Type :");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Total Fare :");

        jButton2.setBackground(new java.awt.Color(120, 128, 134));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDropLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbVehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFare, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPickLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbDropLocation, cmbPickLocation, cmbVehicle, txtDistance, txtFare});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPickLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDropLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFare, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33))
        );

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Book Ride");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 566, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPickLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPickLocationActionPerformed
        // TODO add your handling code here:
        if(cmbPickLocation.getSelectedIndex() > 0){
            cmbDropLocation.setEnabled(true);
        } else {
            cmbDropLocation.setEnabled(false);
        }

    }//GEN-LAST:event_cmbPickLocationActionPerformed

    private void cmbDropLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDropLocationActionPerformed
        // TODO add your handling code here:
        if(cmbDropLocation.getSelectedIndex() >0){
            int pickup = value.get(cmbPickLocation.getSelectedIndex()-1);
            int dropoff = value.get(cmbDropLocation.getSelectedIndex()-1);
            int d = Math.abs(pickup-dropoff);
            txtDistance.setText(new DecimalFormat().format(d));
        } else{
            txtDistance.setText("0");
        }
    }//GEN-LAST:event_cmbDropLocationActionPerformed

    private void cmbVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehicleActionPerformed
        // TODO add your handling code here:

        int distance = Integer.parseInt(txtDistance.getText());
        switch(cmbVehicle.getSelectedIndex()){
            case 0:

            break;
            case 1:
            TotalFare =  60 + 9*distance;
            break;
            case 2:
            TotalFare =  80 + 13*distance;
            break;
            case 3:
            TotalFare =  106 + 15*distance;
            break;
            case 4:
            TotalFare =  120 + 20*distance;
            break;
            case 5:
            TotalFare =  135 + 23*distance;
            break;
        }

        txtFare.setText("Rs : " + new DecimalFormat().format(TotalFare));

    }//GEN-LAST:event_cmbVehicleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!validateFields()){
        
        } else if(txtDistance.getText().equals("0")){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Pickup location & Dropoff Location must bhe different");
        } else {
            try {
                DataBaseConnection.insertData("INSERT INTO Rides (Captain , Passenger, Vehicle, Pickup, Dropoff, Distance, Fare, Status) VALUES ('"+"null"+"','"+
                    name+"','"+
                    cmbVehicle.getSelectedItem()+"','"+
                    cmbPickLocation.getSelectedItem()+"','"+
                    cmbDropLocation.getSelectedItem()+"','"+
                    txtDistance.getText().trim()+"','"+TotalFare+"','Requested')");
                
                ResultSet rs = DataBaseConnection.getData("SELECT MAX(RideNo) FROM Rides");
                while(rs.next()){
                    new Message("Ride Booked...", 1555, this);
                    new Ride(this,false , null, rs.getString(1)).setVisible(true);
                    break;
                }
                this.dispose();
            } catch (Exception e) {
                System.out.println("asf"+e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDropLocation;
    private javax.swing.JComboBox cmbPickLocation;
    private javax.swing.JComboBox cmbVehicle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtFare;
    // End of variables declaration//GEN-END:variables

    
    private boolean validateFields(){
        
        if(cmbPickLocation.getSelectedIndex() == 0){
            getToolkit().beep();
            cmbPickLocation.requestFocus();
        } else if(cmbDropLocation.getSelectedIndex() == 0){
            getToolkit().beep();
            cmbDropLocation.requestFocus();
        } else if(cmbVehicle.getSelectedIndex() == 0){
            getToolkit().beep();
            cmbVehicle.requestFocus();
        } else{
            return true;
        }
        
        return false;
    }
}
